### ISSUE TITLE
Pulumi Registry: Exoscale Listing is missing

### ISSUE THREAD

**Issue by matthiasbaldi** [pulumiverse/pulumi-exoscale#19]
The Link in the Readme to the URL https://www.pulumi.com/registry/packages/exoscale/api-docs/ ends up with an error 404.
https://github.com/pulumiverse/pulumi-exoscale/blob/192808231dcb4966391d9efbd9a43b2e48c27544/README.md?plain=1#L57
Also, I get on a "non-pre-cached" system an error while installing the Exoscale plugin manually `pulumi plugin install resource exoscale v0.1.2`.
```text
error: [resource plugin exoscale-0.1.2] downloading from: failed to download plugin: exoscale-0.1.2: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-exoscale-v0.1.2-windows-amd64.tar.gz
```

Is there a misunderstanding on my side (changed URL)? Or is there something wrong?
Btw: I cannot find it here https://www.pulumi.com/registry/ too.

Thanks for checking.

**Comment by dirien** [comment]
Hi @matthiasbaldi,

thanks for creating the issue. Yes the PR to add this provider to the Pulumi registry is still on progress. See https://github.com/pulumi/registry/pull/1553 for the current state.

I prepared everything in the Readmes for the moment it's available in the registry.

**Comment by matthiasbaldi** [comment]
Ahhh okay. I thought this is merged already.
Okay then this is related. 👍

**Comment by matthiasbaldi** [comment]
As we saw today, it got merged 👍 👌
https://www.pulumi.com/registry/packages/exoscale/api-docs/compute/

**Comment by dirien** [comment]
Hi @matthiasbaldi,

-> https://www.pulumi.com/registry/packages/exoscale/ 

Ready to use, I just tested it! ❤️
